name: build

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - name: Build
        run: ./build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build
